Resources:
    Table:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: coffee-api-table 
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
            TimeToLiveSpecification:
                AttributeName: 'expires'
                Enabled: true
    PersonalInfoTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: coffee-api-personalinfotable
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
    EventBus:
        Type: AWS::Events::EventBus
        Properties:
            Name: CoffeeBus
Outputs:
    TableName:
        Value: !Ref Table
    TableArn:
        Value: !GetAtt Table.Arn
    PersonalInfoTableName:
        Value: !Ref PersonalInfoTable
    PersonalInfoTableArn:
        Value: !GetAtt PersonalInfoTable.Arn
    EventBusName:
        Value: !Ref EventBus
        Export:
            Name: CoffeeBusName
    EventBusArn:
        Value: !GetAtt EventBus.Arn
        Export:
            Name: CoffeeBusArn
