Resources:
  ApiRoot:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: '{name}-{stage}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowOrigins:
          - '*'
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiRoot
      StageName: $default
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:coffee-app-menu-logic-getMenu-
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiRoot}/*/*/
  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiRoot
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
      - ''
      - - 'arn:'
        - !Ref 'AWS::Partition'
        - ':apigateway:'
        - !Ref 'AWS::Region'
        - ':lambda:path/2015-03-31/functions/'
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:coffee-app-menu-logic-getMenu-
        - /invocations
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 6500
  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiRoot
      RouteKey: GET /
      Target: !Join
        - /
        - - integrations
          - !Ref Integration
    DependsOn:
      - Integration
