Resources:
  CognitoUserPoolMyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
        UserPoolName: coffee-user-pool
        UsernameAttributes:
            - email
        AutoVerifiedAttributes:
            - email

        AdminCreateUserConfig:
            AllowAdminCreateUserOnly: true
            InviteMessageTemplate:
                EmailSubject: You are being invited to join an app
            UnusedAccountValidityDays: 365

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
        ClientName: coffe-user-pool-client
        UserPoolId:
            Ref: CognitoUserPoolMyUserPool
        ExplicitAuthFlows:
            - ADMIN_NO_SRP_AUTH
            - USER_PASSWORD_AUTH
        GenerateSecret: false

Outputs:
    userPoolId:
        Value:
            Ref: CognitoUserPoolMyUserPool
    userPoolClientId:
        Value:
            Ref: CognitoUserPoolClient
    userPoolRegion:
        Value: us-east-1'